name: demo
description: A new Flutter project.

environment:
  sdk: '>= 2.4.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  built_collection: ^4.2.2
  transparent_image: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
